version: "3.8"
services:
  php:
    image: milicavasovic/organizator-casova
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lollypop
      MYSQL_DATABASE: organizator_casova
      command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./organizator_casova.sql:/docker-entrypoint-initdb.d/organizator_casova.sql
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMAHOST: db
      PMA_USER: root
      PMA_PASSWORD: lollypop
      PMA_DATABASE: organizator_casova

volumes:
  mysql-data:
